# Generated by Django 4.2.1 on 2023-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kibshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
